import React from "react"
import Link from "next/link"
import Head from "next/dist/shared/lib/head"
import { MainLayout } from "../components/MainLayout"
import '../styles/Home.module.css'
import Image from "next/image"

export default function Home(){
    return(
        <MainLayout>
            <Head>
                <title>Госуслуги</title>
                <meta name="description" content="Generated by create next app"/>
                 <link rel="icon" href="/gosuslugi.png"/>               
            </Head>
            <h1>Главная</h1>
        </MainLayout>
    )
}